### ISSUE TITLE
CM times still show the redundant zero

### ISSUE THREAD

**Issue by vitorebom** [GeChallengeM/zero-remover#1]
[CM run](https://imgur.com/X5KyRx1)

**Comment by GeChallengeM** [comment]
Do you happen to use the CoX Timers & Additions plugin by De0? That plugin alters those messages as well, causing the bug. I don't know how to fix it on my part. It could get fixed if De0 gives the option to remove reduntant 0's through his plugin.

**Comment by vitorebom** [comment]
Yes I do, that would explain it. Should I report this issue on that plugin instead?

**Comment by GeChallengeM** [comment]
If you want to use the CoX Timers plugin and also want all redundant zeros to be removed, that seems to be your best bet yes.

**Comment by GeChallengeM** [comment]
I did a CoX today and noticed the bug was something else, unrelated to De0's plugin. I'm fixing it now.
